version: '3.7'

services:
  web:
    build:
      context: ./PrestaShop
      dockerfile: ../Dockerfile
      target: prod
      args:
        PHP_VERSION: 7.1.30
    ports:
      - '8002:80'
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306'
    env_file:
      - .env